const LOG_ANSI = {
  ok: "#00ff00",
  warning: "#ff0000",
  progress: "#ffff00",
  completed: "#ff00ff",
  romanticLight: "#ec4899",
  romanticMid: "#db2777",
  romanticDeep: "#be185d",
  romanticBold: "#9d174d",
  romanticFinal: "#831843",
} as const;

export const CODE_LINES = [
  { text: '[  OK  ] Mounted /sys/kernel/love', color: LOG_ANSI.ok, delay: 500 },
  { text: '[  OK  ] Started Load Affection Modules', color: LOG_ANSI.ok, delay: 800 },
  { text: '[  OK  ] Reached target Romantic Gestures', color: LOG_ANSI.ok, delay: 700 },
  { text: '[ .... ] Starting Heartbeat Synchronization...', color: LOG_ANSI.progress, delay: 1000 },
  { text: '[  OK  ] Heartbeat Synchronization Complete', color: LOG_ANSI.ok, delay: 900 },
  { text: '[ .... ] Loading Romantic Memory Database...', color: LOG_ANSI.progress, delay: 1200 },
  { text: '[  OK  ] Loaded Romantic Memory Database', color: LOG_ANSI.ok, delay: 800 },
  { text: '[WARNING] Excessive Cuteness Detected!', color: LOG_ANSI.warning, delay: 1000 },
  { text: '[ .... ] Compiling Romantic Gestures...', color: LOG_ANSI.progress, delay: 1500 },
  { text: '[  OK  ] Compiled Romantic Gestures', color: LOG_ANSI.ok, delay: 900 },
  { text: '[ .... ] Initializing Love Letter Generator...', color: LOG_ANSI.progress, delay: 700 },
  { text: '[  OK  ] Initialized Love Letter Generator', color: LOG_ANSI.ok, delay: 1100 },
  { text: '[ .... ] Pairing Soulmate Connection...', color: LOG_ANSI.progress, delay: 1300 },
  { text: '[  OK  ] Paired Soulmate Connection', color: LOG_ANSI.ok, delay: 1000 },
  { text: '[ .... ] Activating Infinite Love Loop...', color: LOG_ANSI.progress, delay: 1200 },
  { text: '[  OK  ] Activated Infinite Love Loop', color: LOG_ANSI.ok, delay: 800 },
  { text: '[  OK  ] Reached target LOVE OS Boot', color: LOG_ANSI.ok, delay: 500 },
  { text: 'All systems loving! ❤', color: LOG_ANSI.completed, delay: 1000 },
] as const;

export const ROMANTIC_TEXT = [
  { text: '[  OK  ] Initializing 8th March Celebration...', color: LOG_ANSI.romanticLight, delay: 500 },
  { text: '[  OK  ] Loaded Memories of Us', color: LOG_ANSI.romanticMid, delay: 800 },
  { text: '[ .... ] Compiling Reasons Why I Love You...', color: LOG_ANSI.romanticDeep, delay: 1000 },
  { text: '[  OK  ] Compiled 1000+ Reasons', color: LOG_ANSI.romanticBold, delay: 900 },
  { text: '[ .... ] Generating Love Letter...', color: LOG_ANSI.romanticDeep, delay: 1200 },
  { text: '[  OK  ] Love Letter Ready', color: LOG_ANSI.romanticBold, delay: 800 },
  { text: '[ .... ] Sending Virtual Hugs and Kisses...', color: LOG_ANSI.romanticDeep, delay: 1000 },
  { text: '[  OK  ] Hugs and Kisses Delivered', color: LOG_ANSI.romanticBold, delay: 700 },
  { text: '[  OK  ] Reached target 8th March Celebration', color: LOG_ANSI.romanticLight, delay: 500 },
  { text: 'To the most amazing person in my life,', color: LOG_ANSI.romanticLight, delay: 1000 },
  { text: 'You make every day brighter and more beautiful.', color: LOG_ANSI.romanticMid, delay: 1000 },
  { text: 'Your smile is my favorite sight,', color: LOG_ANSI.romanticDeep, delay: 1000 },
  { text: 'And your love is my greatest joy.', color: LOG_ANSI.romanticBold, delay: 1000 },
  { text: 'Thank you for trusting me with your heart,', color: LOG_ANSI.romanticLight, delay: 1000 },
  { text: 'For always being my safe place,', color: LOG_ANSI.romanticMid, delay: 1000 },
  { text: 'And for believing in us, no matter what.', color: LOG_ANSI.romanticDeep, delay: 1000 },
  { text: 'Your strength inspires me every day,', color: LOG_ANSI.romanticBold, delay: 1000 },
  { text: 'And your kindness makes the world better.', color: LOG_ANSI.romanticLight, delay: 1000 },
  { text: 'I am so grateful for your love,', color: LOG_ANSI.romanticMid, delay: 1000 },
  { text: 'For your patience, your laughter,', color: LOG_ANSI.romanticDeep, delay: 1000 },
  { text: 'And for being my partner in everything.', color: LOG_ANSI.romanticBold, delay: 1000 },
  { text: 'Happy 8th March, my love! ❤️', color: LOG_ANSI.romanticFinal, delay: 1000 },
] as const;